travis:
  secure:
    BINSTAR_TOKEN: RfkVwwR/sySZw+pQuiikW9OZqvkR63gIXXE02reDYY8HDTPuuv6Qn6j/1Bpgsk02BhAVKiHFv1WNSU7/fYIz24HAVG9ER8UfqoHYR7WrOJdHE28zDUMtxgwAM3kl3MzgYoGRZrmJMFLH6yyE/H/aHGbKGm5MtF4VlSCRil0P4OWV9pAIINjr0LblN7P8sTzgxSvDu4k+w7XwVxBmM6Lsn+OTG9CaqGNsr3aIoMstT8HyLWoYyvrEeI9rpT9/btIEZev+anqVpaqRIdM/u+Z3N9KG5v6Gm81ASzXAyyhVcAvC+ciR/4Vu2KPH9j4hdcpz/7qb8Mn1WS1aegfoqgcj/3yzIuuHqrTF28+UJtQzqo/SSCiEUxwcNM0Y83oHHRygQ3/XskHKgFSvsUyppZIhJNmP/ikIbShmfgpbtbaEPYFRVoE+U9UvHwl/ZWW9yogeTcip2S7H/kDS90u8rPExsG4If4F6HRhYARTAkcqggZ0juG9SsAHsMJ6/7DAbmKy5QfP5Dv6J4UQyvDMQ1/N7KFKgSrUICw2+xbgyB52Cti9EOHkWwOaQynEC3P5NKdlbpy3SwpP0mCk+uYfvBapLbQED0WSHo1Oc0B+0LWHjlPULswUcSm9NSLMOenslnAmpLRQwk+f82mT2UYufRUHLdGnChtf9KELqQq3UK1Ryehk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
