travis:
  secure:
    BINSTAR_TOKEN: AXlczkNE1BlDHkGwt3XauonJU7AhPZugP+/1FFNDoXWDDlxCdlpmfV4JJHexsMySLTHGXAQ+eEJnki2ezfyi7FVq0zpZNswc/Gix1B/0qVxYOI+APwedh8q1TzjidfduHwxqS/q/7IelqM6+8YIDPRI7Dx8fILYrm5qQiZ7SaM9KHzV7A9BbahpH+WtX2dBTplbJUUyPXUMgfUfw8DXS3HFs2Pde7/4656Qk4ij9m+Q2Z/Is5FsXq/agT3G/6bFJvZhQsMch68OjGhziV9unBtjfGYcbnPuvCDAsacSfyWje4ri3hVZ7aXCwMwmWthuKecnV21TwXL8pzBrE2dGiOJedV9Wl473xJZtLKHWbha6dwgQ4tNdokIroaRWHqFI919UE0SGK9hBBQF9p4F6SiZf7S65KjkAq9Rgd4utCV4r6xLuqkxJQlVpvh+ru2PAkOs2v5a/9dYw5rFNsR/3b7BOGUkm4APLtKAfMYaboMizu5vEtOGVMl/OMGQy4gnC/1lr8VV2ms1+02dEpEjh6kQQLSrV7OavbjT+pzcHkBlOQvzmgqT9C2XcRMspLsXrXpcd7zxD8yxhz9/WL+0OhfbDnucwDrFdcDuH8ZyK9St+VHCiBYOscMi9Aj32Xkd8ZYmUb9tTYkDE4RkceqM5MDDYseyj0hRsKrio6nyS+rt0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
