travis:
  secure:
    BINSTAR_TOKEN: EavDw+jQcoaPLbWPG6ypCUWfBEdXzRbMKot64DxUlwp2TkFN1EoD2yvQF0v1TzUpAt9Xh4cMTascxAjE3boloIywObKnFvOZdqAidPvVKlu8dnX0NgzdnBhPkIwRz8VuywHQWMGsMBNe1efIoHhK4bWEoMekDwghznQ7awS4lf9guW/+Ity2I9YYbnaNOQye4I7TaZ4PayezGCj00fvQvPqr4AzI7ZC5Ik9D1QMp5Qhpw4Ji/rgf/51o9XuWn8/xIDxG/mG89qzfYx/vHTU94XXBBJsRqW2PHK+sNjq1Vsh6VWb0X0vVdOVL7QzgjUpy1nCTmbD7fGPQCVioO9+ouhkUdPBSnup8urGpeUbhYg/98Z8PEeGV4LSHXtCMrgj6lUCEKGR8cjiNrbkhS7wWNuxOqFDwr6OCQ6/1qaCVRJRr42fsZmhvb3YMYbH7NR1mJHg1elDGqvz9DBEQ1CMtJScXSIqL0nwWkcNRcO+fhnJ1lpM7DtcfO6R0UEikwLm0kM5EuL5NpbA40zf4GgXTCKAzn/Car9mcq6wolwlgBO2wD4vhpbd+F39Pjaq9EYzKd7tVxHc4/I006LJK/IUznfxt4NKeET9hCt+vZ6n9UmaAXOPHBVGMQKAQaWKhPYWG8ZrUXUeIRIeLzMZRXkjG2XRZEsIBDGI6iaSUZ9tHXfw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
